name: Release

on:
  push:
    tags: ["v*"]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: alpaca-trader
          target: ${{ matrix.target }}
          archive: $name-$target.$ext
          token: ${{ secrets.GITHUB_TOKEN }}
